common:
  daemonize: false
  pid_dir: {{.RuntimeDir}}
  log_media: file
  log_level: info
  log_dir: {{.RuntimeDir}}/log/
  working_dir: .
config_paths:
  config_dir: {{.RuntimeDir}}/
  data_dir: {{.RuntimeDir}}/data/
  simulation_path: {{.RuntimeDir}}/simulation.yaml
  hub_dir: {{.RuntimeDir}}/hub/
  index_path: {{.RuntimeDir}}/hub/.index.json
  notification_dir: {{.RuntimeDir}}/notifications/
  plugin_dir: /usr/local/lib/crowdsec/plugins/
crowdsec_service:
  parser_routines: 1
cscli:
  output: human
db_config:
  log_level: info
  type: sqlite
  db_path: {{.RuntimeDir}}/data/crowdsec.db
  #user: 
  #password:
  #db_name:
  #host:
  #port:
  flush:
    max_items: 5000
    max_age: 7d
plugin_config:
  user: nobody # plugin process would be ran on behalf of this user
  group: nogroup # plugin process would be ran on behalf of this group
api:
  client:
    insecure_skip_verify: false
    credentials_path: {{.RuntimeDir}}/local_api_credentials.yaml
  server:
    log_level: info
    listen_uri: 127.0.0.1:{{.Port}}
    profiles_path: {{.RuntimeDir}}/profiles.yaml
prometheus:
  enabled: true
  level: full
  listen_addr: 127.0.0.1
  listen_port: 6060
