parser_results: parser_results.yaml
acquisition_file: acquis.yaml
bucket_results: bucket_results.yaml
#configuration
index: "./config/hub/.index.json"
configurations:
  parsers:
  - crowdsecurity/syslog-logs
  - crowdsecurity/nginx-logs
  scenarios:
  - ltsich/http-wordpress_install_scan

