type: trigger
#debug: true
name: crowdsecurity/modsecurity
description: "Web exploitation via modsecurity"
#modsec for nginx only logs the numerical value of the severity
filter: evt.Meta.log_type == 'modsecurity' && (evt.Parsed.ruleseverity == 'CRITICAL' || evt.Parsed.ruleseverity == '2')
blackhole: 2m
labels:
  type: http:exploit
  label: ModSecurity CRS 
  remediation: true
  scope: ip
